use_frameworks!

platform :ios, '11.0'

target 'ios-voice-processor_Example' do
  pod 'ios-voice-processor', :path => '../'
end

target 'ios-voice-processor_ExampleUITests' do
  pod 'ios-voice-processor', :path => '../'
end
