name: iOS Demo

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ios-demo.yml'
      - 'example/**'
      - '!example/REAMDE.md'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/ios-demo.yml'
      - 'example/**'
      - '!example/REAMDE.md'

defaults:
  run:
    working-directory: example

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: XCode Build
        run: xcodebuild build
          -configuration Debug
          -project ios-voice-processor.xcodeproj
          -sdk iphoneos
          -scheme ios-voice-processor-Example
          -destination "platform=iOS Simulator,name=iPhone 12"
          CODE_SIGNING_ALLOWED=NO

